version: '3'

services:
  asai-app:
    container_name: asai-app
    environment:
      - ENVIRONMENT=LOCAL DEV
      - CGO_CFLAGS=-D_LARGEFILE64_SOURCE
    build:
      context: .
      dockerfile: ./env/docker/Dockerfile
    ports:
      - 8082:8082
    volumes:
      - .:/app
    depends_on:
      - asai-db
    networks:
      - asai-network
    extra_hosts:
      - host.docker.internal:host-gateway

  asai-db:
    image: postgres:9.6.12
    container_name: asai-db
    environment:
      - POSTGRES_DB=asai-db
      - POSTGRES_USER=asai-admin
      - POSTGRES_PASSWORD=asai-password
      - DATABASE_PORT=5432
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - asai-network

  # asai-ollama:
    # image: ollama/ollama
    # container_name: asai-ollama
    # ports:
    #   - 11434:11434
    # volumes:
    #   - ollama_data:/app
    # networks:
    #   - asai-network

volumes:
  # ollama_data:
  #   driver: local
  db-data:
    driver: local

networks:
  asai-network:
    driver: bridge